export enum CardElementType {
    Column = 'Column',
    ColumnSet = 'ColumnSet',
    Container = 'Container',
    FactSet = 'FactSet',
    Image = 'Image',
    ImageSet = 'ImageSet',
    TextBlock = 'TextBlock',
    InputText = 'Input.Text',
    InputNumber = 'Input.Number',
    DateInput = 'Input.Date',
    TimeInput = 'Input.Time',
    InputToggle = 'Input.Toggle',
    InputChoiceSet = 'Input.ChoiceSet',
}
